name: Create S3 Bucket with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Create S3 Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ID }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: terraform init 

      - name: Terraform planing
        run:  terraform plan

      - name: Apply terraform configuration
        run: terraform apply -auto-approve 
